- hosts: my_hosts
  become: yes
  tasks:
    - name: Ensure Python 3 is installed
      apt:
        name: python3
        state: present

    - name: Ensure python3-apt is installed
      apt:
        name: python3-apt
        state: present

    - name: Verify Python 3 installation
      command: python3 --version
      register: python_version
      changed_when: false

    - name: Print Python 3 version
      debug:
        msg: "Python version is {{ python_version.stdout }}"

    - name: Verify python3-apt installation
      command: python3 -c "import apt; print('python3-apt is installed')"
      register: apt_check
      changed_when: false

    - name: Print python3-apt installation status
      debug:
        msg: "{{ apt_check.stdout }}"

